apiVersion: v1
kind: Service
metadata:
  name: {{ include "papermc-server.name" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "papermc-server.name" . }}
  ports:
    - port: 25565
      nodePort: {{ .Values.service.ports.nodePort }}
