name: papermc-server
namespace: default
eula: false

container:
  image: djaytan/papermc-server:dev
  resources:
    requests:
      ephemeralStorage: 10Gi
      cpu: 4
      memory: 8Gi
    limits:
      ephemeralStorage: 10Gi
      cpu: 4
      memory: 8Gi

service:
  ports:
    nodePort: 30000

# Health checks configuration.
# If the server is deemed "unhealthy", it will be automatically restarted
# to ensure high availability and minimize downtime.
healthcheck:
  # Time interval (in seconds) between consecutive health checks.
  checkInterval: 1
  # Time in seconds before the server is considered unhealthy.
  # Must be a multiple of checkInterval.
  failureThreshold:
    startup: 60   # During startup phase.
    liveness: 5   # During normal operation.
